import "../styles/globals.scss";
import MainLayout from "@/src/components/layout/main-layout";

export const metadata = {
  title: "Events App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <MainLayout>
        {children}
      </MainLayout>
      </body>
    </html>
  );
}
